# Generated by Django 5.1 on 2024-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
